/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/desk.glb -o src/components/Desk.jsx -r public 
*/

import React, { useRef } from "react";
import { useGLTF, useVideoTexture } from "@react-three/drei";

export function Desk(props) {
  const { nodes, materials } = useGLTF("/models/desk.glb");
  const screentexture = useVideoTexture("/images/vscode.mp4");
  return (
    <group {...props} dispose={null}>
      <group position={[0.68, 0.04, 4.36]}>
        <group
          position={[-0.536, 1.037, -4.292]}
          rotation={[-Math.PI / 2, 0, 1.37]}
          scale={48.098}
        >
          <group position={[-0.001, 0, 0]}>
            <mesh
              geometry={nodes["Blank_Picture_Frame|Node007|Dupli|003"].geometry}
              material={materials["mat21.008"]}
            />
            <mesh
              geometry={
                nodes["Blank_Picture_Frame|Node007|Dupli|003_1"].geometry
              }
              material={materials["mat22.005"]}
            />
            <mesh
              geometry={
                nodes["Blank_Picture_Frame|Node007|Dupli|003_2"].geometry
              }
              material={materials["mat15.006"]}
            />
            <mesh
              geometry={
                nodes["Blank_Picture_Frame|Node007|Dupli|003_3"].geometry
              }
              material={materials["mat24.004"]}
            />
          </group>
        </group>
        <group
          position={[-1.036, 0.921, -4.943]}
          rotation={[-Math.PI / 2, 0, -1.61]}
          scale={20.517}
        >
          <mesh
            geometry={nodes["Keyboard001|group1030983910|Dupli|22"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1075691498|Dupli|58"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1149852049|Dupli|53"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1152190519|Dupli|19"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1180881246|Dupli|50"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1238060299|Dupli|28"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1238428394|Dupli|61"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1272091893|Dupli|35"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1316349499|Dupli|39"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1323238240|Dupli|32"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group145618305|Dupli|23"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1486350934|Dupli|63"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group150579309|Dupli|11"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1529968652|Dupli|6"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1571332333|Dupli|33"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1581414308|Dupli|8"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1589752359|Dupli|26"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1629393722|Dupli|64"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1629609685|Dupli|21"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1675960081|Dupli|12"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1740918352|Dupli|46"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1753917514|Dupli|5"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1754683637|Dupli|40"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1764140354|Dupli|60"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1870575723|Dupli|65"].geometry}
            material={materials["mat16.003"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1899843208|Dupli|36"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1956214489|Dupli|14"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group196400395|Dupli|15"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group1976194690|Dupli|18"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group205302596|Dupli|31"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group2074153597|Dupli|20"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group2085389804|Dupli|57"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group2091112366|Dupli|59"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group2106755496|Dupli|4"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group2146178072|Dupli|38"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group252681800|Dupli|7"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group268332703|Dupli|44"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group287159489|Dupli|13"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group295085766|Dupli|9"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group311988427|Dupli|1"].geometry}
            material={materials["mat22.007"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group34220672|Dupli|34"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group384612072|Dupli|10"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group418912012|Dupli|30"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group42243725|Dupli|37"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group425587018|Dupli|"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group449779970|Dupli|3"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group45382983|Dupli|52"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group475225180|Dupli|41"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group573547017|Dupli|49"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group588539140|Dupli|47"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group601803475|Dupli|25"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group616518658|Dupli|56"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group687259746|Dupli|51"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group706802639|Dupli|17"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group729811280|Dupli|48"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group77921105|Dupli|42"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group790925258|Dupli|54"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group801095923|Dupli|29"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group806343109|Dupli|27"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group826580911|Dupli|24"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group873458270|Dupli|55"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group873558583|Dupli|62"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group877249531|Dupli|66"].geometry}
            material={materials["mat9.004"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group954813675|Dupli|16"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group96314515|Dupli|2"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group96968687|Dupli|43"].geometry}
            material={materials["mat21.010"]}
          />
          <mesh
            geometry={nodes["Keyboard001|group993315105|Dupli|45"].geometry}
            material={materials["mat21.010"]}
          />
        </group>
        <group
          position={[-0.546, 0.913, -4.926]}
          rotation={[-Math.PI / 2, 0, 3.105]}
          scale={1.135}
        >
          <mesh
            geometry={nodes["Monitor001|iMac|Dupli|"].geometry}
            material={materials["Mat.007"]}
          />
          <mesh
            geometry={nodes.screen.geometry}
            // material={materials["Mat.009"]}
          >
            <meshBasicMaterial map={screentexture} toneMapped={false}/>
          </mesh>
        </group>
        <group
          position={[-0.897, 0.308, -3.493]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
          scale={212.203}
        >
          <mesh
            geometry={nodes.Cabinet_Bed_Drawer_Tabl003.geometry}
            material={materials["wood.003"]}
          />
          <mesh
            geometry={nodes.Cabinet_Bed_Drawer_Tabl003_1.geometry}
            material={materials["_defaultMat.003"]}
          />
          <mesh
            geometry={nodes.Cabinet_Bed_Drawer_Tabl003_2.geometry}
            material={materials["metal.003"]}
          />
        </group>
        <group
          position={[-1.954, 0.633, -4.88]}
          rotation={[-Math.PI / 2, 0, 1.643]}
          scale={2.911}
        >
          <mesh
            geometry={nodes.Chair004.geometry}
            material={materials["Executive.004"]}
          />
          <mesh
            geometry={nodes.Chair004_1.geometry}
            material={materials["Executive__1.004"]}
          />
          <mesh
            geometry={nodes.Chair004_2.geometry}
            material={materials["Executive__2.004"]}
          />
          <mesh
            geometry={nodes.Chair004_3.geometry}
            material={materials["Executive__3.004"]}
          />
        </group>
        <group
          position={[-1.037, 0.957, -2.813]}
          rotation={[Math.PI, 0, 0]}
          scale={10000}
        >
          <mesh
            geometry={nodes["Houseplant-bfLOqIV5uP003"].geometry}
            material={materials["Black.008"]}
          />
          <mesh
            geometry={nodes["Houseplant-bfLOqIV5uP003_1"].geometry}
            material={materials["Brown.003"]}
          />
          <mesh
            geometry={nodes["Houseplant-bfLOqIV5uP003_2"].geometry}
            material={materials["Plant_Green.003"]}
          />
        </group>
        <group
          position={[-0.735, 1.162, -5.596]}
          rotation={[-Math.PI / 2, 0, 2.492]}
          scale={[8561.476, 8561.474, 8561.471]}
        >
          <mesh
            geometry={nodes.Light_Desk004.geometry}
            material={materials["Black.009"]}
          />
          <mesh
            geometry={nodes.Light_Desk004_1.geometry}
            material={materials["LightMetal.003"]}
          />
          <mesh
            geometry={nodes.Light_Desk004_2.geometry}
            material={materials["White.006"]}
          />
        </group>
        <mesh
          geometry={nodes.Mouse.geometry}
          material={materials["Material.004"]}
          position={[-1.038, 0.913, -4.465]}
          rotation={[-Math.PI / 2, 0, -1.417]}
          scale={[14736.432, 14736.434, 14736.435]}
        />
        <mesh
          geometry={nodes.Mousepad.geometry}
          material={materials["Mousepad.003"]}
          position={[-1.026, 0.915, -4.473]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[17.231, 20.977, 0.228]}
        />
        <group
          position={[-0.801, 0.614, -4.913]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
          scale={3.21}
        >
          <mesh
            geometry={nodes.Node004.geometry}
            material={materials["_5_Drawer.003"]}
          />
          <mesh
            geometry={nodes.Node004_1.geometry}
            material={materials["_5_Drawer_1.003"]}
          />
        </group>
        <group
          position={[-1.072, 0.946, -5.544]}
          rotation={[-Math.PI / 2, 0, 0.024]}
          scale={219.88}
        >
          <mesh
            geometry={nodes.Paper003.geometry}
            material={materials["mat21.011"]}
          />
          <mesh
            geometry={nodes.Paper003_1.geometry}
            material={materials["mat15.008"]}
          />
        </group>
        <group
          position={[-0.927, 0.921, -5.299]}
          rotation={[Math.PI / 2, 0, 1.096]}
          scale={[5618.101, 5618.101, 5618.099]}
        >
          <mesh
            geometry={nodes.Phone003.geometry}
            material={materials["White.007"]}
          />
          <mesh
            geometry={nodes.Phone003_1.geometry}
            material={materials["Grey.004"]}
          />
          <mesh
            geometry={nodes.Phone003_2.geometry}
            material={materials["Black.010"]}
          />
        </group>
        <mesh
          geometry={nodes["Cup001|Cup|Dupli|"].geometry}
          material={materials["Mat.005"]}
          position={[-0.8, 0.909, -4.316]}
          rotation={[-Math.PI / 2, 0, -0.522]}
          scale={0.219}
        />
      </group>
      <group
        position={[0.038, 0.945, -0.378]}
        rotation={[Math.PI, -0.027, Math.PI]}
        scale={0.03}
      >
        <mesh
          geometry={nodes["Desk_Speakers_01_Cube-Mesh002"].geometry}
          material={materials["795548.002"]}
        />
        <mesh
          geometry={nodes["Desk_Speakers_01_Cube-Mesh002_1"].geometry}
          material={materials["1A1A1A.002"]}
        />
        <mesh
          geometry={nodes["Desk_Speakers_01_Cube-Mesh002_2"].geometry}
          material={materials["455A64.002"]}
        />
      </group>
      <group
        position={[-0.129, 0.945, -1.169]}
        rotation={[Math.PI, -0.928, Math.PI]}
        scale={0.03}
      >
        <mesh
          geometry={nodes["Desk_Speakers_01_Cube-Mesh003"].geometry}
          material={materials["795548.003"]}
        />
        <mesh
          geometry={nodes["Desk_Speakers_01_Cube-Mesh003_1"].geometry}
          material={materials["1A1A1A.003"]}
        />
        <mesh
          geometry={nodes["Desk_Speakers_01_Cube-Mesh003_2"].geometry}
          material={materials["455A64.003"]}
        />
      </group>
      <mesh
        geometry={nodes["1337"].geometry}
        material={materials["1337"]}
        position={[0.029, 1.132, -0.572]}
        rotation={[Math.PI / 2, -0.179, Math.PI / 2]}
        scale={[0.04, 0.86, 0.05]}
      />
    </group>
  );
}

useGLTF.preload("/models/desk.glb");