/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/lamp.glb -o src/components/Lamp.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Lamp(props) {
  const { nodes, materials } = useGLTF('/models/lamp.glb')
  return (
    <group {...props} dispose={null} scale={0.16} position={[0.2,0.03, 0]} rotation-y={-Math.PI/2}>
      <mesh geometry={nodes.group1982449423.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group159819829.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group778822713.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group1663465607.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group934490515.geometry} material={materials.mat18} />
      <mesh geometry={nodes.group1212059862.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1234694877.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1219371868.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group289902031.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group747334372.geometry} material={materials.mat22} />
      <mesh geometry={nodes.group652232159.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group274337514.geometry} material={materials.mat21} />
      <mesh geometry={nodes.group1775857955.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1054111511.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group1042645973.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group2094850929.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group64761282.geometry} material={materials.mat23} />
      <mesh geometry={nodes.group67639701.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1667276076.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh1667276076_1.geometry} material={materials.mat18} />
    </group>
  )
}

useGLTF.preload('/models/lamp.glb')
