/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 public/models/avatartyping.gltf -o src/components/test.jsx -r public 
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function Typing(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/models/avatartyping.gltf");
  const { actions, names } = useAnimations(animations, group);
  // console.log(names);
  // console.log(actions);

  // useEffect(() => {
  //   if (names && names.length > 1) {
  //     actions[names[1]].reset().play();
  //   }
  // }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          scale={1.24}
          position={[1.2, -0.96, 0.5]}
          rotation={[Math.PI / 2, -Math.PI/2, Math.PI / 2]}
        >
          <group name="mycharacter">
            <primitive object={nodes.Hips} />
            <skinnedMesh
              name="Wolf3D_Body"
              geometry={nodes.Wolf3D_Body.geometry}
              material={materials["Wolf3D_Body.003"]}
              skeleton={nodes.Wolf3D_Body.skeleton}
            />
            <skinnedMesh
              name="Wolf3D_Hair"
              geometry={nodes.Wolf3D_Hair.geometry}
              material={materials["Wolf3D_Hair.003"]}
              skeleton={nodes.Wolf3D_Hair.skeleton}
            />
            <skinnedMesh
              name="Wolf3D_Outfit_Bottom"
              geometry={nodes.Wolf3D_Outfit_Bottom.geometry}
              material={materials["Wolf3D_Outfit_Bottom.003"]}
              skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton}
            />
            <skinnedMesh
              name="Wolf3D_Outfit_Footwear"
              geometry={nodes.Wolf3D_Outfit_Footwear.geometry}
              material={materials["Wolf3D_Outfit_Footwear.003"]}
              skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton}
            />
            <skinnedMesh
              name="Wolf3D_Outfit_Top"
              geometry={nodes.Wolf3D_Outfit_Top.geometry}
              material={materials["Wolf3D_Outfit_Top.003"]}
              skeleton={nodes.Wolf3D_Outfit_Top.skeleton}
            />
            <skinnedMesh
              name="EyeLeft"
              geometry={nodes.EyeLeft.geometry}
              material={materials["Wolf3D_Eye.003"]}
              skeleton={nodes.EyeLeft.skeleton}
            />
            <skinnedMesh
              name="EyeRight"
              geometry={nodes.EyeRight.geometry}
              material={materials["Wolf3D_Eye.003"]}
              skeleton={nodes.EyeRight.skeleton}
            />
            <skinnedMesh
              name="Wolf3D_Head"
              geometry={nodes.Wolf3D_Head.geometry}
              material={materials["Wolf3D_Skin.003"]}
              skeleton={nodes.Wolf3D_Head.skeleton}
            />
            <skinnedMesh
              name="Wolf3D_Teeth"
              geometry={nodes.Wolf3D_Teeth.geometry}
              material={materials["Wolf3D_Teeth.003"]}
              skeleton={nodes.Wolf3D_Teeth.skeleton}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/avatartyping.gltf");
